### ISSUE TITLE
32 bit linux is not supported currently

### ISSUE THREAD

**Issue by PvdBerg1998** [tinaun/futures-native-timers#3]
You're casting to `i64` instead of `usize`/`isize` here: https://github.com/tinaun/futures-native-timers/blob/master/src/sys/linux.rs#L113, which means this does not compile on 32 bits systems.

**Comment by PvdBerg1998** [comment]
Actually something weird is happening here. https://doc.rust-lang.org/1.7.0/libc/type.time_t.html is defined to be i64 ?

**Comment by PvdBerg1998** [comment]
I think this is a bug in libc. I've created an issue: https://github.com/rust-lang/libc/issues/1289

**Comment by tinaun** [comment]
time_t is defined differently on different platforms - https://docs.rs/libc/0.2.49/i686-unknown-linux-gnu/libc/type.time_t.html

**Comment by tinaun** [comment]
anyway, i fixed the time_t issue, but 32 bit linux still won't work until i remove the transmute inside the signal handler - the libc crate exposes the siginfo_t union just as an array of i32, and the data layout is different depending on the platform

**Comment by PvdBerg1998** [comment]
Ah I guess there's different docs per platform ? Thanks for the update.

**Comment by gnzlbg** [comment]
> Ah I guess there's different docs per platform ?

Yes: https://rust-lang.github.io/libc/#platform-specific-documentation

**Comment by PvdBerg1998** [comment]
@tinaun Do you have any idea how to fix this? I have some free time so I could help if you give me some pointers. @gnzlbg Ah, cool. I just googled `libc time_t` and only found one, the 64 bit definition. I guess it makes sense.

**Comment by gnzlbg** [comment]
docs.rs supports showing docs for different platforms (there is a platform drop-down on the docs there), but I just added a PR to make this more clear: https://github.com/rust-lang/libc/pull/1290

**Comment by PvdBerg1998** [comment]
@tinaun Not 100% sure, but I think you can replace the `transmute` with a `let val: libc::sigval = ptr::read(&raw_bytes[3] as *const _ as *const _);`

**Comment by tinaun** [comment]
this should be fixed now - at the very least it builds

**Comment by PvdBerg1998** [comment]
Can confirm!
